[config]
schemaVersion = "0.0.1"

[package]
namespace = "gravityblastr"
name = "UnpackMod"
versionNumber = "0.0.1"
description = "Lets you unpack bricks at a packaging station even when packaging is in the slot."
websiteUrl = "https://github.com/gravityblastr/schedule-1-mods"
containsNsfwContent = false

[package.dependencies]
"LavaGang-MelonLoader" = "0.6.6"
"the_croods-SwapperPlugin" = "1.2.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../.work/thunderstore"

[[build.copy]]
source = "./bin/Release/net6.0/GravityBlastr.UnpackMod.dll"
target = "IL2CPP/GravityBlastr.UnpackMod.IL2CPP.dll"

[[build.copy]]
source = "./bin/Release/netstandard2.1/GravityBlastr.UnpackMod.dll"
target = "Mono/GravityBlastr.UnpackMod.Mono.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["schedule-i"]
categories = ["mods", "il2cpp", "mono"]

