[config]
schemaVersion = "0.0.1"

[package]
namespace = "gravityblastr"
name = "LightPersistMod"
versionNumber = "0.0.1"
description = "Saves flashlight and headlight state across game loads."
websiteUrl = "https://github.com/gravityblastr/schedule-1-mods"
containsNsfwContent = false

[package.dependencies]
"LavaGang-MelonLoader" = "0.6.6"
"the_croods-SwapperPlugin" = "1.2.2"

[build]
icon = "./icon.png"
readme = "./README.md"
outdir = "../../.work/thunderstore"

[[build.copy]]
source = "./bin/Release/net6.0/GravityBlastr.LightPersistMod.dll"
target = "IL2CPP/GravityBlastr.LightPersistMod.IL2CPP.dll"

[[build.copy]]
source = "./bin/Release/netstandard2.1/GravityBlastr.LightPersistMod.dll"
target = "Mono/GravityBlastr.LightPersistMod.Mono.dll"

[publish]
repository = "https://thunderstore.io"
communities = ["schedule-i"]
categories = ["mods"]

